### ISSUE TITLE
Request to resolve error on CentOS 7 GPU server

### ISSUE THREAD

**Issue by Hamzadarpk** [dvershinin/apt-get-centos#1]
Please can you help me resolve this problem? I am using command on CentOS 7 GPU server.

![ss error](https://user-images.githubusercontent.com/116285000/197716843-9a93d098-7f40-4890-9ced-2f4a4ba7b965.png)

**Comment by dvershinin** [comment]
Hi @Hamzadarpk , you need to run the commands as the `root` user, or a user with sudo privileges (and in that case prepend them with `sudo` command).
